### ISSUE TITLE
non-ascii characters in most fields (dashboard titles, line labels...) cause broken graphs

### ISSUE THREAD

**Issue by g76r** [Graphite-Tattle/Tattle#63]
this is an issue only for non-english users, but there are plenty of them around me (incl. myself) :-)

**Comment by g76r** [comment]
seems rather to be graphite-related than tattle-related:

``` 
Traceback (most recent call last):
  File "/usr/local/applications/eagle/exec/eagle-graphite-1/deps/django/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/applications/eagle/exec/eagle-graphite-1/webapp/graphite/render/views.py", line 200, in renderView
    image = doImageRender(requestOptions['graphClass'], graphOptions)
  File "/usr/local/applications/eagle/exec/eagle-graphite-1/webapp/graphite/render/views.py", line 408, in doImageRender
    img = graphClass(**graphOptions)
  File "/usr/local/applications/eagle/exec/eagle-graphite-1/webapp/graphite/render/glyph.py", line 195, in __init__
    self.drawGraph(**params)
  File "/usr/local/applications/eagle/exec/eagle-graphite-1/webapp/graphite/render/glyph.py", line 643, in drawGraph
    self.drawTitle( str(params['title']) )
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)
```
